Meow/Meow.Web/Areas/Cats/Models/HomeCats/CatsListingViewModel.cs
namespace Meow.Web.Areas.Cats.Models.HomeCats
{
    public class CatsListingViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string ImageUrl { get; set; }
    }
}

Meow/Meow.Web/Areas/Cats/Models/HomeCats/HomeCatDeleteFormModel.cs
namespace Meow.Web.Areas.Cats.Models.HomeCats
{
    public class HomeCatDeleteFormModel
    {
        public string Name { get; set; }

        public int Age { get; set; }
    }
}

Meow/Meow.Web/Areas/Cats/Models/HomeCats/HomeCatDetailsViewModel.cs
namespace Meow.Web.Areas.Cats.Models.HomeCats
{
    using Data.Models.Enums;

    public class HomeCatDetailsViewModel
    {
        public string Name { get; set; }

        public int Age { get; set; }

        public string ImageUrl { get; set; }

        public string Description { get; set; }

        public string Location { get; set; }

        public Gender Gender { get; set; }

        public string OwnerId { get; set; }

        public string Owner { get; set; }
    }
}

Meow/Meow.Web/Areas/Cats/Models/HomeCats/HomeCatEditFormModel.cs
namespace Meow.Web.Areas.Cats.Models.HomeCats
{
    using Data;
    using Data.Models.Enums;
    using System.ComponentModel.DataAnnotations;

    public class HomeCatEditFormModel
    {
        [Required]
        [MinLength(DataConstants.CatNameMinLength)]
        [MaxLength(DataConstants.CatNameMaxLength)]
        public string Name { get; set; }

        [Range(DataConstants.CatMinAge, DataConstants.CatMaxAge)]
        public int Age { get; set; }

        //[DataType(DataType.Upload)]
        //public byte[] Image { get; set; }

        [MaxLength(DataConstants.CatDescriptionMaxLength)]
        public string Description { get; set; }

        public Gender Gender { get; set; }
    }
}

Meow/Meow.Web/Areas/Admin/Controllers/UsersController.cs
namespace Meow.Web.Areas.Admin.Controllers
{
    using Data.Models;
    using Infrastructure.Extensions;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Models;
    using Services.Contracts;
    using System.Linq;
    using System.Threading.Tasks;

    public class UsersController : BaseAdminController
    {
        private readonly IAdminUserService users;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<User> userManager;

        public UsersController(
            IAdminUserService users,
            UserManager<User> userManager,
            RoleManager<IdentityRole> roleManager)
        {
            this.users = users;
            this.userManager = userManager;
            this.roleManager = roleManager;
        }

        public IActionResult Manage()
        {
            var users = this.users.All();

            var roles = this.roleManager
                .Roles
                .Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.Name
                })
                .ToList();

            return View(new UsersListingViewModel
            {
                Users = users,
                Roles = roles
            });
        }

        [HttpPost]
        public async Task<IActionResult> AddToRole(AddUserToRoleFormModel model)
        {
            var roleExists = await this.roleManager.RoleExistsAsync(model.Role);
            var user = await this.userManager.FindByIdAsync(model.UserId);
            var userExists = user != null;

            if (!roleExists || !userExists)
            {
                ModelState.AddModelError(string.Empty, "Invalid identity details.");
            }

            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(Manage));
            }

            await this.userManager.AddToRoleAsync(user, model.Role);

            TempData.AddSuccessMessage($"User {user.UserName} successfully added to the {model.Role} role.");
            return RedirectToAction(nameof(Manage));
        }
    }
}

Meow/Meow.Web/Areas/Cats/Controllers/HomeCatsController.cs
namespace Meow.Web.Areas.Cats.Controllers
{
    using Core;
    using Data.Models;
    using Infrastructure.Extensions;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Models.HomeCats;
    using Services.Cats.Contracts;

    [Area(WebConstants.CatsArea)]
    [Authorize]
    public class HomeCatsController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly IHomeCatService cats;

        public HomeCatsController(IHomeCatService cats, UserManager<User> userManager)
        {
            this.cats = cats;
            this.userManager = userManager;
        }

        // all home cats
        [Authorize]
        public IActionResult All()
        {
            var model = this.cats.All();

            return this.View(model);
        }

        // details about home cat
        public IActionResult Details(int id)
        {
            var cat = this.cats.ById(id);

            return this.ViewOrNotFound(cat);
        }

        public IActionResult Add()
        {
            return this.View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Add(HomeCatFormModel model)
        {
            var ownerId = this.userManager.GetUserId(User);

            var success = this.cats.Add(
                model.Name, model.Image, model.Age, model.Description, model.Gender, ownerId);

            if (!success)
            {
                return this.BadRequest();
            }

            //this.TempData.AddSuccessMessage($"The cat {model.Name} was added successfully!");

            return this.RedirectToAction(nameof(All));
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            var cat = this.cats.ById(id);

            if (cat == null)
            {
                return this.NotFound();
            }

            if (User.Identity.Name != cat.Owner
                && User.Identity.Name != WebConstants.AdministratorUsername)
            {
                // user doesn't have the rights
                return this.RedirectToAction(nameof(this.All));
            }

            return this.View(new HomeCatFormModel
            {
                Name = cat.Name,
                Age = cat.Age,
                Description = cat.Description,
                Gender = cat.Gender
            });
        }

        [Authorize]
        [HttpPost]
        public IActionResult Edit(int id, HomeCatFormModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var catExists = this.cats.Exists(id);

            if (!catExists)
            {
                return this.NotFound();
            }

            this.cats.Edit(id, model.Name, model.Age, model.Description, model.Image, model.Gender);

            return this.RedirectToAction(nameof(this.All));
        }

        [Authorize]
        public IActionResult Delete(int id)
        {
            var cat = this.cats.ById(id);

            if (cat == null)
            {
                return this.NotFound();
            }

            if (User.Identity.Name != cat.Owner
                && User.Identity.Name != WebConstants.AdministratorUsername)
            {
                // user doesn't have the rights
                return this.RedirectToAction(nameof(this.All));
            }

            return this.View(new HomeCatDeleteFormModel
            {
                Name = cat.Name,
                Age = cat.Age
            });
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        public IActionResult ConfirmDelete(int id)
        {
            var catExists = this.cats.Exists(id);

            if (!catExists)
            {
                return this.RedirectToAction(nameof(this.All));
            }

            var result = this.cats.Remove(id);

            return this.RedirectToAction(nameof(this.All));
        }

        public IActionResult Manage()
        {
            var model = this.cats.All();

            return this.View(model);
        }
    }
}

Meow/Meow.Web/Areas/Volunteer/Controllers/AdoptionCatsController.cs
namespace Meow.Web.Areas.Volunteer.Controllers
{
    using Data.Models;
    using Meow.Web.Areas.Volunteer.Models;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Services.Contracts;

    public class AdoptionCatsController : BaseVolunteerController
    {
        private readonly UserManager<User> userManager;
        private readonly IAdoptionCatService adoptionCats;

        public AdoptionCatsController(UserManager<User> userManager, IAdoptionCatService adoptionCats)
        {
            this.userManager = userManager;
            this.adoptionCats = adoptionCats;
        }

        public IActionResult Manage()
        {
            var model = this.adoptionCats.All();

            return this.View(model);
        }

        public IActionResult Add()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult Add(AdoptionCatFormModel model)
        {
            var ownerId = this.userManager.GetUserId(User);

            var success = this.adoptionCats.Add(
                model.Name, model.Age, model.ImageUrl, model.Description, model.Gender, ownerId);

            if (!success)
            {
                return this.BadRequest();
            }

            //this.TempData.AddSuccessMessage($"The cat {model.Name} was added successfully!");

            //return this.RedirectToAction();
        }

        public IActionResult Edit(int id)
        {
            var adoptionCat = this.adoptionCats.ById(id);

            if (adoptionCat == null)
            {
                return this.NotFound();
            }

            if (User.Identity.Name != adoptionCat.Owner)
            {
                // user doesn't have the rights
               // return this.RedirectToAction(nameof(this.All));
            }

            return this.View(new AdoptionCatFormModel
            {
                Name = adoptionCat.Name,
                Age = adoptionCat.Age,
                ImageUrl = adoptionCat.ImageUrl,
                Description = adoptionCat.Description,
                Gender = adoptionCat.Gender
            });
        }

        [HttpPost]
        public IActionResult Edit(int id, AdoptionCatFormModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var adoptionCatExists = this.adoptionCats.Exists(id);

            if (!adoptionCatExists)
            {
                return this.NotFound();
            }

            this.adoptionCats.Edit(
                id, model.Name, model.Age, model.ImageUrl, model.Description, model.Gender);

           // return this.RedirectToAction(nameof(this.All));
        }
        
        public IActionResult Delete(int id)
        {
            // todo: check if user has rights to delete

            var adoptionCat = this.adoptionCats.ById(id);

            if (adoptionCat == null)
            {
                return this.NotFound();
            }

            if (User.Identity.Name != adoptionCat.Owner)
            {
                // user doesn't have the rights
             //   return this.RedirectToAction(nameof(this.All));
            }

            return this.View(new AdoptionCatFormModel
            {
                Name = adoptionCat.Name,
                Age = adoptionCat.Age,
                ImageUrl = adoptionCat.ImageUrl,
                Description = adoptionCat.Description,
                Gender = adoptionCat.Gender
            });
        }

        [HttpPost]
        public IActionResult Delete(int id, AdoptionCatFormModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var adoptionCatExists = this.adoptionCats.Exists(id);

            if (!adoptionCatExists)
            {
                return this.NotFound();
            }

            var result = this.adoptionCats.Remove(id);

            // todo

           // return this.RedirectToAction(nameof(this.All));
        }

    }
}

Meow/Meow.Web/Controllers/UsersController.cs
namespace Meow.Web.Controllers
{
    using Core;
    using Data.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Models;
    using Services.Contracts;
    using System.Linq;
    using System.Threading.Tasks;

    public class UsersController : Controller
    {
        private readonly IUserService users;
        private readonly UserManager<User> userManager;
        private readonly RoleManager<IdentityRole> roleManager;

        public UsersController(IUserService users, UserManager<User> userManager, RoleManager<IdentityRole> roleManager)
        {
            this.users = users;
            this.userManager = userManager;
            this.roleManager = roleManager;
        }

        [Authorize]
        public IActionResult All()
        {
            var model = this.users.All();

            return this.View(model);
        }

        [Authorize]
        public async Task<IActionResult> Profile(string username)
        {
            var user = await this.userManager.FindByNameAsync(username);

            if (user == null)
            {
                return this.NotFound();
            }
            var roles = await this.userManager.GetRolesAsync(user);
            //var userRole = "Normal";

            // we can use this at this moment, because I have only one multiple roles - admin :)
            //if (role != null && role.Count() != 0)
            //{
            //    userRole = role[0];
            //}

            var model = await this.users.ProfileAsync(user.Id);
            model.UserRoles = roles;

            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> HomeCats(string username)
        {
            var user = await this.userManager.FindByNameAsync(username);

            if (user == null)
            {
                return this.NotFound();
            }

            var model = await this.users.HomeCatsAsync(user.Id);

            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> AdoptedCats(string username)
        {
            var user = await this.userManager.FindByNameAsync(username);

            if (user == null)
            {
                return this.NotFound();
            }

            var model = await this.users.AdoptedCatsAsync(user.Id);

            return View(model);
        }

        public IActionResult Edit(string username)
        {
            var task = this.userManager.FindByNameAsync(username);
            var user = task.Result;

            if (user == null)
            {
                return this.NotFound();
            }

            if (User.Identity.Name != user.UserName &&
                !this.User.IsInRole(WebConstants.AdministratorRole))
            {
                // user doesn't have the rights
                return RedirectToAction("All");
            }

            return this.View(new UserFormModel
            {
                Username = user.UserName,
                Name = user.Name,
                Location = user.Location,
                Birthdate = user.Birthdate,
                Gender = user.Gender
            });
        }

        [HttpPost]
        public IActionResult Edit(string username, UserFormModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var user = this.userManager.FindByNameAsync(username);
            var userExists = this.users.Exists(user.Result.Id);

            if (!userExists)
            {
                return this.NotFound();
            }

            this.users.Edit(model.Username, model.Name, model.Location, model.Birthdate, model.Gender, model.Image);

            return RedirectToAction("All");
        }

        [Authorize]
        public async Task<IActionResult> Delete(string username)
        {
            var user = await this.userManager.FindByNameAsync(username);

            if (user == null)
            {
                return this.NotFound();
            }

            // we won't delete the admin and volunteer
            if (user.UserName == WebConstants.AdministratorUsername
                || user.UserName == WebConstants.VolunteerUsername)
            {
                return this.RedirectToAction(nameof(All));
            }
      
            if (User.Identity.Name != user.UserName
                && User.Identity.Name != WebConstants.AdministratorUsername)
            {
                // user doesn't have the rights
                return this.RedirectToAction(nameof(this.All));
            }

            return this.View(model:username);
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(string username)
        {       
            var user = await this.userManager.FindByNameAsync(username);
            var userExists = this.users.Exists(user.Id);

            if (!userExists)
            {
                return this.NotFound();
            }

            var result = this.users.Remove(user.Id);

            return this.RedirectToAction(nameof(this.All));
        }
    }
}

Meow/Meow.Web/Views/Users/AdoptedCats.cshtml
@{
    ViewData["Title"] = "Adopted Cats";
}

<div class="container">

    <h1 class="my-4 text-center text-lg-left">Adopted Cats</h1>

    <div class="row text-center text-lg-left">

        @foreach (var cat in this.Model)
        {
            <div class="col-lg-3 col-md-4 col-xs-6 hovereffect">

                <a asp-area="Cats" asp-controller="AdoptionCats" asp-action="Adopt" asp-route-id="@cat.Id" class="d-block mb-4 h-100">

                    @{
                        var imgSrc = cat.Image != null ? ImageConvertions.ByteArrayToImage(cat.Image) : WebConstants.DefaultCatUrl;
                    }
                    <img class="img-fluid img-thumbnail img-cat img-circle" src="@imgSrc" alt="@cat.Name">
                </a>
            </div>
        }
    </div>
</div>

Meow/Meow.Web/Views/Users/All.cshtml
@{
    ViewData["Title"] = "All";
}

<div class="container">

    <h1 class="my-4 text-center text-lg-left">Users</h1>

    <div class="row text-center text-lg-left">

        @foreach (var user in this.Model)
        {
            <div class="col-lg-3 col-md-4 col-xs-6 hovereffect">
                <a asp-action="Profile" asp-route-username="@user.UserName" class="d-block mb-4 h-100">
                    @{
                        var imgSrc = ImageConvertions.ByteArrayToImage(user.ProfilePhoto);
                    }
                    <img class="img-fluid img-thumbnail img-cat img-circle" src="@imgSrc" alt="@user.Name">
                </a>
            </div>
        }
    </div>
</div>

Meow/Meow.Web/Views/Users/Delete.cshtml
@model UserDeleteFormModel
@{
    ViewData["Title"] = "Delete user";
}

<div class="body-blur"></div>
<div class="grad"></div>

<br>
<div class="login">
    <form asp-route-returnUrl="@ViewData["ReturnUrl"]" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <input asp-for="Name" class="form-control" disabled />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="hidden" asp-for="Id" class="form-control" disabled />
            <span asp-validation-for="Id" class="text-danger"></span>
        </div>

            <button type="submit" class="login-button" style="width:250px">Submit</button>
    </form>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Meow/Meow.Web/Views/Users/Edit.cshtml
@model UserFormModel
@{
    ViewData["Title"] = "Edit";
}

<h2>@ViewData["Title"]</h2>
<div class="body-blur"></div>
<div class="grad"></div>
<br>

<div class="login">
    <form asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <input asp-for="Username" class="form-control" placeholder="Name" />
            <span asp-validation-for="Username" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input asp-for="Name" class="form-control" placeholder="Name" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input asp-for="Location" class="form-control" placeholder="Location" />
            <span asp-validation-for="Location" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input asp-for="Birthdate" class="form-control" placeholder="birthdate" />
            <span asp-validation-for="Birthdate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <select asp-for="Gender" asp-items="@Html.GetEnumSelectList<Gender>()" style="width: 250px; height: 25px"></select>
            <span asp-validation-for="Gender" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input asp-for="Image" type="file" class="form-control" />
        </div>

            <button type="submit" class="login-button" style="width: 250px">Edit</button>
    </form>
</div>
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Meow/Meow.Web/Views/Users/HomeCats.cshtml
@{
    ViewData["Title"] = "HomeCats";
}

<div class="container">

    <h1 class="my-4 text-center text-lg-left">Home Cats</h1>

    <div class="row text-center text-lg-left">

        @foreach (var cat in this.Model)
        {
            <div class="col-lg-3 col-md-4 col-xs-6 hovereffect">
                <a asp-area="Cats" asp-controller="HomeCats" asp-action="Details" asp-route-id="@cat.Id" class="d-block mb-4 h-100">
                    @{
                        var imgSrc = cat.Image != null ? ImageConvertions.ByteArrayToImage(cat.Image) : WebConstants.DefaultCatUrl;
                    }
                    <img class="img-fluid img-thumbnail img-cat img-circle" src="@imgSrc" alt="@cat.Name">
                </a>
            </div>
        }
    </div>
</div>

Meow/Meow.Web/Views/Users/Profile.cshtml
@{
    ViewData["Title"] = "Profile";
}       

<div class="container">
    <div class="row">
        <div class="col-md-5  toppad  pull-right col-md-offset-3 ">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">@this.Model.Name</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-3 col-lg-3 " align="center">
                            @{
                                var imgSrc = this.Model.ProfilePhoto != null ? ImageConvertions.ByteArrayToImage(this.Model.ProfilePhoto) : WebConstants.DefaultProfilePhotoUrl;
                            }
                            <img alt="@this.Model.UserName photo" src="@imgSrc" class="img-fluid img-thumbnail img-circle">
                        </div>
                        <div class=" col-md-9 col-lg-9 ">
                            <table class="table table-user-information">
                                <tbody>
                                    <tr>
                                        <td>Username:</td>
                                        <td>@this.Model.UserName</td>
                                    </tr>
                                    <tr>
                                        <td>Role:</td>
                                        <td>@(string.Join(", ", Model.UserRoles))</td>
                                    </tr>
                                    <tr>
                                        <td>Date of Birth:</td>
                                        <td>@this.Model.Birthdate.ToShortDateString()</td>
                                    </tr>
                                    <tr>
                                    <tr>
                                        <td>Gender:</td>
                                        <td>@this.Model.Gender</td>
                                    </tr>
                                    <tr>
                                        <td>Email:</td>
                                        <td><a href="mailto:@this.Model.Email">@this.Model.Email</a></td>
                                    </tr>
                                </tbody>
                            </table>
                            <a asp-controller="Users" asp-action="HomeCats" asp-route-username="@this.Model.UserName" class="btn btn-outline-success">Home cats</a>
                            <a asp-controller="Users" asp-action="AdoptedCats" asp-route-username="@this.Model.UserName" class="btn btn-outline-success">Adopted cats</a>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <!--todo - adoption cats-->
                    <a data-original-title="Broadcast Message" data-toggle="tooltip" class="btn btn-sm btn-default"><i class="glyphicon glyphicon-envelope"></i></a>
                    <span class="pull-right">
                        @if (this.Model.UserName == User.Identity.Name ||
                               this.User.IsInRole(WebConstants.AdministratorRole))
                        {
                            <!--todo - edit user - add route-->
                            <a asp-controller="Users" asp-action="Edit" asp-route-username="@this.Model.UserName" data-original-title="Edit this user" data-toggle="tooltip" class="btn btn-sm btn-default"><i class="glyphicon glyphicon-edit"></i></a>
                            <a asp-controller="Users" asp-action="Delete" asp-route-username="@this.Model.UserName" data-original-title="Remove this user" data-toggle="tooltip" class="btn btn-sm btn-default"><i class="glyphicon glyphicon-remove"></i></a>
                        }
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>