Meow/Meow.Web/Areas/Cats/Models/HomeCats/CatsListingViewModel.cs
namespace Meow.Web.Areas.Cats.Models.HomeCats
{
    public class CatsListingViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string ImageUrl { get; set; }
    }
}

Meow/Meow.Web/Areas/Cats/Models/HomeCats/HomeCatDeleteFormModel.cs
namespace Meow.Web.Areas.Cats.Models.HomeCats
{
    public class HomeCatDeleteFormModel
    {
        public string Name { get; set; }

        public int Age { get; set; }
    }
}

Meow/Meow.Web/Areas/Cats/Models/HomeCats/HomeCatDetailsViewModel.cs
namespace Meow.Web.Areas.Cats.Models.HomeCats
{
    using Data.Models.Enums;

    public class HomeCatDetailsViewModel
    {
        public string Name { get; set; }

        public int Age { get; set; }

        public string ImageUrl { get; set; }

        public string Description { get; set; }

        public string Location { get; set; }

        public Gender Gender { get; set; }

        public string OwnerId { get; set; }

        public string Owner { get; set; }
    }
}

Meow/Meow.Web/Areas/Cats/Models/HomeCats/HomeCatEditFormModel.cs
namespace Meow.Web.Areas.Cats.Models.HomeCats
{
    using Data;
    using Data.Models.Enums;
    using System.ComponentModel.DataAnnotations;

    public class HomeCatEditFormModel
    {
        [Required]
        [MinLength(DataConstants.CatNameMinLength)]
        [MaxLength(DataConstants.CatNameMaxLength)]
        public string Name { get; set; }

        [Range(DataConstants.CatMinAge, DataConstants.CatMaxAge)]
        public int Age { get; set; }

        //[DataType(DataType.Upload)]
        //public byte[] Image { get; set; }

        [MaxLength(DataConstants.CatDescriptionMaxLength)]
        public string Description { get; set; }

        public Gender Gender { get; set; }
    }
}

Meow/Meow.Web/Areas/Cats/Models/HomeCats/HomeCatFormModel.cs
namespace Meow.Web.Areas.Cats.Models.HomeCats
{
    using Data;
    using Data.Models.Enums;
    using Microsoft.AspNetCore.Http;
    using System.ComponentModel.DataAnnotations;

    public class HomeCatFormModel
    {
        [Required]
        [MinLength(DataConstants.CatNameMinLength)]
        [MaxLength(DataConstants.CatNameMaxLength)]
        public string Name { get; set; }

        [Range(DataConstants.CatMinAge, DataConstants.CatMaxAge)]
        public int Age { get; set; }

        [DataType(DataType.Upload)]
        public IFormFile Image { get; set; }

        [MaxLength(DataConstants.CatDescriptionMaxLength)]
        public string Description { get; set; }

        public Gender Gender { get; set; }
    }
}

Meow/Meow.Web/Models/HomeCats/AddHomeCatFormModel.cs
namespace Meow.Web.Models.HomeCats
{
    using Data;
    using Data.Models.Enums;
    using System.ComponentModel.DataAnnotations;

    public class AddHomeCatFormModel
    {
        [Required]
        [MinLength(DataConstants.CatNameMinLength)]
        [MaxLength(DataConstants.CatNameMaxLength)]
        public string Name { get; set; }

        [Range(DataConstants.CatMinAge, DataConstants.CatMaxAge)]
        public int Age { get; set; }

        [Required]
        [MinLength(DataConstants.ImageUrlMinLength)]
        [MaxLength(DataConstants.ImageUrlMaxLength)]
        [Display(Name = "Image URL")]
        public string ImageUrl { get; set; }

        [MaxLength(DataConstants.CatDescriptionMaxLength)]
        public string Description { get; set; }

        public Gender Gender { get; set; }
    }
}

Meow/Meow.Web/Areas/Cats/Controllers/HomeCatsController.cs
namespace Meow.Web.Areas.Cats.Controllers
{
    using Core;
    using Data.Models;
    using Infrastructure.Extensions;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Models.HomeCats;
    using Services.Cats.Contracts;

    [Area(WebConstants.CatsArea)]
    [Authorize]
    public class HomeCatsController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly IHomeCatService cats;

        public HomeCatsController(IHomeCatService cats, UserManager<User> userManager)
        {
            this.cats = cats;
            this.userManager = userManager;
        }

        // all home cats
        [Authorize]
        public IActionResult All()
        {
            var model = this.cats.All();

            return this.View(model);
        }

        // details about home cat
        public IActionResult Details(int id)
        {
            var cat = this.cats.ById(id);

            return this.ViewOrNotFound(cat);
        }

        public IActionResult Add()
        {
            return this.View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Add(HomeCatFormModel model)
        {
            var ownerId = this.userManager.GetUserId(User);

            var success = this.cats.Add(
                model.Name, model.Image, model.Age, model.Description, model.Gender, ownerId);

            if (!success)
            {
                return this.BadRequest();
            }

            //this.TempData.AddSuccessMessage($"The cat {model.Name} was added successfully!");

            return this.RedirectToAction(nameof(All));
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            var cat = this.cats.ById(id);

            if (cat == null)
            {
                return this.NotFound();
            }

            if (User.Identity.Name != cat.Owner
                && User.Identity.Name != WebConstants.AdministratorUsername)
            {
                // user doesn't have the rights
                return this.RedirectToAction(nameof(this.All));
            }

            return this.View(new HomeCatFormModel
            {
                Name = cat.Name,
                Age = cat.Age,
                Description = cat.Description,
                Gender = cat.Gender
            });
        }

        [Authorize]
        [HttpPost]
        public IActionResult Edit(int id, HomeCatFormModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var catExists = this.cats.Exists(id);

            if (!catExists)
            {
                return this.NotFound();
            }

            this.cats.Edit(id, model.Name, model.Age, model.Description, model.Image, model.Gender);

            return this.RedirectToAction(nameof(this.All));
        }

        [Authorize]
        public IActionResult Delete(int id)
        {
            var cat = this.cats.ById(id);

            if (cat == null)
            {
                return this.NotFound();
            }

            if (User.Identity.Name != cat.Owner
                && User.Identity.Name != WebConstants.AdministratorUsername)
            {
                // user doesn't have the rights
                return this.RedirectToAction(nameof(this.All));
            }

            return this.View(new HomeCatDeleteFormModel
            {
                Name = cat.Name,
                Age = cat.Age
            });
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        public IActionResult ConfirmDelete(int id)
        {
            var catExists = this.cats.Exists(id);

            if (!catExists)
            {
                return this.RedirectToAction(nameof(this.All));
            }

            var result = this.cats.Remove(id);

            return this.RedirectToAction(nameof(this.All));
        }

        public IActionResult Manage()
        {
            var model = this.cats.All();

            return this.View(model);
        }
    }
}

Meow/Meow.Web/Controllers/UsersController.cs
namespace Meow.Web.Controllers
{
    using Core;
    using Data.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Models;
    using Services.Contracts;
    using System.Linq;
    using System.Threading.Tasks;

    public class UsersController : Controller
    {
        private readonly IUserService users;
        private readonly UserManager<User> userManager;
        private readonly RoleManager<IdentityRole> roleManager;

        public UsersController(IUserService users, UserManager<User> userManager, RoleManager<IdentityRole> roleManager)
        {
            this.users = users;
            this.userManager = userManager;
            this.roleManager = roleManager;
        }

        [Authorize]
        public IActionResult All()
        {
            var model = this.users.All();

            return this.View(model);
        }

        [Authorize]
        public async Task<IActionResult> Profile(string username)
        {
            var user = await this.userManager.FindByNameAsync(username);

            if (user == null)
            {
                return this.NotFound();
            }
            var roles = await this.userManager.GetRolesAsync(user);
            //var userRole = "Normal";

            // we can use this at this moment, because I have only one multiple roles - admin :)
            //if (role != null && role.Count() != 0)
            //{
            //    userRole = role[0];
            //}

            var model = await this.users.ProfileAsync(user.Id);
            model.UserRoles = roles;

            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> HomeCats(string username)
        {
            var user = await this.userManager.FindByNameAsync(username);

            if (user == null)
            {
                return this.NotFound();
            }

            var model = await this.users.HomeCatsAsync(user.Id);

            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> AdoptedCats(string username)
        {
            var user = await this.userManager.FindByNameAsync(username);

            if (user == null)
            {
                return this.NotFound();
            }

            var model = await this.users.AdoptedCatsAsync(user.Id);

            return View(model);
        }

        public IActionResult Edit(string username)
        {
            var task = this.userManager.FindByNameAsync(username);
            var user = task.Result;

            if (user == null)
            {
                return this.NotFound();
            }

            if (User.Identity.Name != user.UserName &&
                !this.User.IsInRole(WebConstants.AdministratorRole))
            {
                // user doesn't have the rights
                return RedirectToAction("All");
            }

            return this.View(new UserFormModel
            {
                Username = user.UserName,
                Name = user.Name,
                Location = user.Location,
                Birthdate = user.Birthdate,
                Gender = user.Gender
            });
        }

        [HttpPost]
        public IActionResult Edit(string username, UserFormModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var user = this.userManager.FindByNameAsync(username);
            var userExists = this.users.Exists(user.Result.Id);

            if (!userExists)
            {
                return this.NotFound();
            }

            this.users.Edit(model.Username, model.Name, model.Location, model.Birthdate, model.Gender, model.Image);

            return RedirectToAction("All");
        }

        [Authorize]
        public async Task<IActionResult> Delete(string username)
        {
            var user = await this.userManager.FindByNameAsync(username);

            if (user == null)
            {
                return this.NotFound();
            }

            // we won't delete the admin and volunteer
            if (user.UserName == WebConstants.AdministratorUsername
                || user.UserName == WebConstants.VolunteerUsername)
            {
                return this.RedirectToAction(nameof(All));
            }
      
            if (User.Identity.Name != user.UserName
                && User.Identity.Name != WebConstants.AdministratorUsername)
            {
                // user doesn't have the rights
                return this.RedirectToAction(nameof(this.All));
            }

            return this.View(model:username);
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(string username)
        {       
            var user = await this.userManager.FindByNameAsync(username);
            var userExists = this.users.Exists(user.Id);

            if (!userExists)
            {
                return this.NotFound();
            }

            var result = this.users.Remove(user.Id);

            return this.RedirectToAction(nameof(this.All));
        }
    }
}

Meow/Meow.Web/Areas/Cats/Views/HomeCats/Add.cshtml
@{
    ViewData["Title"] = "Add";
}
<h2>Add</h2>
@Html.Partial("_HomeCatForm")
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Meow/Meow.Web/Areas/Cats/Views/HomeCats/All.cshtml
@{
    ViewData["Title"] = "Home Cats";
}
<div class="container">
    <h1 class="my-4 text-center text-lg-left">Home Cats</h1>
    @if (this.User.Identity.IsAuthenticated)
    {
        <!--add home kitty-->
    <div class="text-center">
        <a asp-action="Add" class="btn btn-default" style="color: black">Add</a>
    </div>
    }
    <div class="row text-center text-lg-left">
        @foreach (var cat in this.Model)
        {
            <div class="col-lg-3 col-md-4 col-xs-6 hovereffect">
                <a asp-action="Details" asp-route-id="@cat.Id" class="d-block mb-4 h-100">
                    @{
                        var imgSrc = cat.Image != null ? ImageConvertions.ByteArrayToImage(cat.Image) : WebConstants.DefaultCatUrl;
                    }
                    <img class="img-fluid img-thumbnail img-cat img-circle" src="@imgSrc" alt="@cat.Name">
                </a>
            </div>
        }
    </div>
</div>

Meow/Meow.Web/Areas/Cats/Views/HomeCats/Delete.cshtml
@model HomeCatDeleteFormModel
@{
    ViewData["Title"] = "Home Cat";
}
<div class="body-blur"></div>
<div class="grad"></div>
<br>
<div class="login">
    <form asp-route-returnUrl="@ViewData["ReturnUrl"]" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <input asp-for="Name" class="form-control" disabled />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input asp-for="Age" class="form-control" disabled />
            <span asp-validation-for="Age" class="text-danger"></span>
        </div>

            <button type="submit" class="login-button" style="width:250px">Submit</button>
    </form>
</div>
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Meow/Meow.Web/Areas/Cats/Views/HomeCats/Details.cshtml
@model HomeCatServiceModel
@{
    ViewData["Title"] = $"The sweet {this.Model.Name}";
}
<div class="container">
    <div class="row">
        <div class="col-md-5  toppad  pull-right col-md-offset-3 ">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">@this.Model.Name</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-3 col-lg-3 " align="center">
                            @{
                                var imgSrc = this.Model.Image != null ? ImageConvertions.ByteArrayToImage(this.Model.Image) : WebConstants.DefaultCatUrl;
                            }
                            <img alt="@this.Model.Name photo" src="@imgSrc" class="img-fluid img-thumbnail img-circle">
                        </div>
                        <div class=" col-md-9 col-lg-9 ">
                            <table class="table table-user-information">
                                <tbody>
                                    <tr>
                                        <td>Age:</td>
                                        <td>@this.Model.Age</td>
                                    </tr>
                                    <tr>
                                        <td>Description:</td>
                                        <td>@this.Model.Description</td>
                                    </tr>
                                    <tr>
                                        <td>Gender:</td>
                                        <td>@this.Model.Gender.ToString()</td>
                                    </tr>
                                    <tr>
                                        <td>Location:</td>
                                        <td>@this.Model.Location</td>
                                    </tr>
                                </tbody>
                            </table>
                            <a asp-area="" asp-controller="Users" asp-action="Profile" asp-route-username="@this.Model.Owner" class="btn btn-default">Owner</a>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <!--todo - adoption cats-->
                    <a data-original-title="Broadcast Message" data-toggle="tooltip" class="btn btn-sm btn-default"><i class="glyphicon glyphicon-envelope"></i></a>
                    <span class="pull-right">
                        @if ((this.Model.Owner == User.Identity.Name) ||
                            this.User.IsInRole(WebConstants.AdministratorRole))
                        {
                            <a asp-action="Edit" asp-route-id="@this.Model.Id" data-original-title="Edit" data-toggle="tooltip" class="btn btn-sm btn-default"><i class="glyphicon glyphicon-edit"></i></a>
                            <a asp-action="Delete" asp-route-id="@this.Model.Id" data-original-title="Remove" data-toggle="tooltip" class="btn btn-sm btn-default"><i class="glyphicon glyphicon-remove"></i></a>
                        }
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>

Meow/Meow.Web/Areas/Cats/Views/HomeCats/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
}
<h2>Edit</h2>
<h2>@ViewData["Title"]</h2>
@Html.Partial("_HomeCatForm")
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Meow/Meow.Web/Areas/Cats/Views/HomeCats/Manage.cshtml
@{
    ViewData["Title"] = "Manage";
}

<h2>Manage</h2>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Owner
            </th>
            <th>
                Details
            </th>
            <th>
                Operations
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var cat in this.Model)
        {
            <tr>
                <th>
                    @cat.Name
                </th>
                <th>
                    @cat.Owner
                </th>
                <th>
                    <a class="btn btn-sm btn-default" asp-area="Cats" asp-controller="HomeCats" asp-action="Details" asp-route-id="@cat.Id">Details</a>
                </th>
                <th>
                    <a class="btn btn-sm btn-default" asp-area="Cats" asp-controller="HomeCats" asp-action="Edit" asp-route-id="@cat.Id">Edit</a>
                    <a class="btn btn-sm btn-default" asp-area="Cats" asp-controller="HomeCats" asp-action="Delete" asp-route-id="@cat.Id">Delete</a>
                </th>
            </tr>
        }
    </tbody>
</table>

Meow/Meow.Web/Areas/Cats/Views/HomeCats/_HomeCatForm.cshtml
@model HomeCatFormModel
@{
    ViewData["Title"] = "Home Cat";
}
<div class="body-blur"></div>
<div class="grad"></div>
<br>
<div class="login">
    <form asp-route-returnUrl="@ViewData["ReturnUrl"]" method="post" enctype="multipart/form-data">
        <!--<div asp-validation-summary="All" class="text-danger"></div> it's unnecessary-->
        <div class="form-group">
            <input asp-for="Name" class="form-control" placeholder="Name" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input asp-for="Age" class="form-control" placeholder="Age" />
            <span asp-validation-for="Age" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input asp-for="Description" class="form-control" placeholder="Description" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <select asp-for="Gender" asp-items="@Html.GetEnumSelectList<Gender>()" style="width:250px; height:25px"></select>
            <span asp-validation-for="Gender" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input asp-for="Image" type="file" class="form-control" />
        </div>

            <button type="submit" class="login-button" style="width:250px">Submit</button>
    </form>
</div>

Meow/Meow.Web/Areas/Cats/Views/HomeCats/_ListingCats.cshtml
@model IEnumerable<CatsListingViewModel>
@{
    ViewData["Title"] = "_ListingCats";
}
<div class="container">
    <h1 class="my-4 text-center text-lg-left">Cats</h1>
    <div class="row text-center text-lg-left">
        @foreach (var cat in this.Model)
        {
            <div class="col-lg-3 col-md-4 col-xs-6 hovereffect">
                <a asp-action="Details" asp-route-id="@cat.Id" class="d-block mb-4 h-100">
                    <img class="img-fluid img-thumbnail img-cat img-circle" src="@cat.ImageUrl" alt="@cat.Name">
                </a>
            </div>
        }
    </div>
</div>